### ISSUE TITLE
Release 2017.10 - RC2

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/Release-Specs#49]
This issue lists the status of all tests for the [Release Candidate 2 of the 2017.10](https://github.com/RIOT-OS/RIOT/releases/tag/2017.10-RC2) release.

**NOTE**
[Please report all findings to this table](https://docs.google.com/spreadsheets/d/1CT21QQCwU-zsjmic1E19BnkchnmAYE0neIdL0AYJq9Y/edit#gid=0)
**NOTE**

Specs tested:
- [x] [01-CI](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md) (@miri64)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-03)
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/01-ci/01-ci.md#task-04)
- [x] [02-Tests](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-01) @A-Paul (https://github.com/RIOT-OS/Release-Specs/issues/50)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-02) @haukepetersen
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md#task-03) @haukepetersen
- [x] [03-Single Hop IPv6 ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md) (@miri64)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01),
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02),
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03),
- [x] [04-Single Hop 6LoWPAN ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) 
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01), @aabadie 
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02), @aabadie 
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03), @aabadie 
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04), @aabadie 
  - [x] [Task 05](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05), @smlng
  - [x] [Task 06](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06), @smlng
  - [x] [Task 07](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07), @aabadie
  - [x] [Task 08](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08),  @aabadie
- [x] [05-Single Hop Route](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md) (@cgundogan)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-01),
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-02),
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/05-single-hop-route/05-single-hop-route.md#task-03),
- [x] [06-Single Hop UDP](https://github.com/RIOT-OS/Release-Specs/blob/master/06-single-hop-udp/06-single-hop-udp.md) (@miri64)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/06-single-hop-udp/06-single-hop-udp.md#task-01),
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/06-single-hop-udp/06-single-hop-udp.md#task-02),
- [x] [07-Multi Hop](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md) (@cgundogan)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-01)
  - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-02)
  - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-03)
  - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/07-multi-hop.md#task-04)
- [ ] [08-Interop](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md)
  - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-01) (@miri64)
  - [ ] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-02) 
  - [ ] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-03) 
  - [ ] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-04) 
  - [ ] [Task 05](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-05) 
  - [ ] [Task 06](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-06) 
  - [ ] [Task 07](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-07) 
  - ~~Task 08~~
  - [ ] [Task 09](https://github.com/RIOT-OS/Release-Specs/blob/master/08-interop/08-interop.md#task-09) 
  - ~~Task 10~~

**Comment by miri64** [comment]
How do we note down who is testing what? Our old approach (putting it into the description) lead to problems in RC1. For now I do it the way we used to, because I hope I'm careful enough to not overwrite collisions accidentally ;-).

**Comment by A-Paul** [comment]
The errors from RC1 are fixed. All performed tests *02-tests Task 01* were successful.

**Comment by haukepetersen** [comment]
@A-Paul thanks!

@miri64 lets note this our names in this list as usual, but only names and tick-marks. If we make sure, that we keep the time editing (press edit, enter name, press save) to a minium, we should be good. Also everyone should re-check after some minutes to make sure that entries still exist... For bugs/issues/todos we keep using the google spreadsheet.

**Comment by haukepetersen** [comment]
Just looked through everything that was merged since RC1: we only touched
- multiple tests
- the cc2536/cc26x0
- cbor (knwon issue)
- fatfs pkg
- ds1307 driver

IMHO we mainly need to re-test everything regarding these modules (mainly task 02). But I don't see the need to do ALL tests again, and would suggest that we only do some quick 'probing' for all tasks > 2. Do you all agree with this approach?

**Comment by cgundogan** [comment]
to add to @haukepetersen's important notes:
reload the page **beore** doing tick marks. Each marking is an **edit** in the sense and overrides previous states probably made by others.

**Comment by haukepetersen** [comment]
@cgundogan yes absolutely, thanks!

**Comment by haukepetersen** [comment]
@smlng: would you mind to 'play' with the cc2536 and the cc26x0 using RC2 a little bit to confirm them working?
@miri64: could you confirm the ds1307 once more?
@A-Paul: when you re-did task 02.01, you also verified that the fatfs pkg is working, correct?

**Comment by cgundogan** [comment]
>IMHO we mainly need to re-test everything regarding these modules (mainly task 02). But I don't see the need to do ALL tests again, and would suggest that we only do some quick 'probing' for all tasks > 2. Do you all agree with this approach?

I agree. I will do some probing for the multi hop tests, but I don't expect any changes from the previous results.

**Comment by haukepetersen** [comment]
Nice. Any changes from the previous results would indeed be very strange :-)

**Comment by smlng** [comment]
> @smlng: would you mind to 'play' with the cc2536 and the cc26x0 using RC2 a little bit to confirm them working?

Yes, will do!

**Comment by smlng** [comment]
Task 04.05 and 04.06 succeeded as before, however packet loss is still above the desired boundaries. That is, for ping payload above 50B its mostly 30 to 50 % loss with smaller payloads sometimes < 10% but often more like 25%. 

This needs further investigation on the cause, i.e. board, driver, or transceiver related or something general.

**Comment by smlng** [comment]
cc2650 is working, too.

**Comment by haukepetersen** [comment]
@smlng: thanks! I propose to take this as a known issue into the release. Is there already an open issue for this?

**Comment by smlng** [comment]
I just tested the tasks with samr21-xpro and PhyNode (pba-d-01-kw2x) and discovered that pings with payloads below 100B work, even with better results regarding packet loss than the remotes (so this might be board related). But starting from 100B nothing gets through, while this worked with the remotes though with high packet loss. This seems to be related to the PhyNode.

**Comment by haukepetersen** [comment]
If I remember correctly, there were fragmentation issues with the phynode knwon some time ago. I have no overview how that turned out, @miri64 do you know something here?

**Comment by miri64** [comment]
Yes, this is still an issue https://github.com/RIOT-OS/RIOT/issues/4822

**Comment by smlng** [comment]
Fragmentation is also an issue for CC2538 (where pings work, but with higher packet loss) and 100B payload should still fit in one, or not?

**Comment by miri64** [comment]
No, I don't think so. It depends a little bit on how the cc2538 driver advertises its MAC header length to the upper layer but e.g. for `at86rf2xx` the switch-over point is at 96B (or even lower) IIRC. There it just advertises the maximum *possible* MAC payload (without security information), so with both 8 byte addresses, both 2 byte PAN IDs a 2 byte FCF and a 2 byte FCS you get only 112B out of your 127B total MAC frame length. This is rounded down to the nearest divisible of 8 (because 6Lo fragmentations works on a unit of 8 bytes) and you get 96 bytes.

**Comment by smlng** [comment]
> you get only 112B out of your 127B total MAC frame length. This is rounded down to the nearest divisible of 8 (because 6Lo fragmentations works on a unit of 8 bytes) and you get 96 bytes.

😕  112/8 = 14?

**Comment by miri64** [comment]
How did I get to 112...? I think I meant 102 ... But even that is wrong: 127 - 2 * 8 - 2 * 2 - 2 - 2 = 103. So 103 was meant ;-).

**Comment by miri64** [comment]
(Also: you can check that your self by incrementing the payload size slowly and sniffing the packets, if it starts to be 6Lo fragmentation packets the threshold is reached ;-))

**Comment by aabadie** [comment]
04-task7 and 04-task8, done with respectively 0.8% and 0.7% packet loss. I also confirm that the XBee gets a global prefix from a RPI + OpenLabs.

**Comment by haukepetersen** [comment]
perfect.

Tasks 02 is also done.

**Comment by miri64** [comment]
Since despite me believing so https://github.com/RIOT-OS/RIOT/pull/7750 wasn't merged into the release Task 1.1 failed due to a full disk. I run it now on a different machine in the background with 7750 cherry-picked, but the results will most likely only be there in the evening.

**Comment by miri64** [comment]
@aabadie I think you destroyed the post above right now....

**Comment by aabadie** [comment]
> I think you destroyed the post above right now....

how ?

**Comment by miri64** [comment]
Well propably not by reloading before editing. I had a lot of ticked tests than reloaded and they disappeared after an edit of yours ;-)

**Comment by miri64** [comment]
(including my taking of the tests)

**Comment by miri64** [comment]
How exactly to manage circumventing the warning that the content had changed I don't know ;-)

**Comment by aabadie** [comment]
Ah, ok I see, sorry. One solution is to replay your tests ;)

**Comment by miri64** [comment]
For tests that run >1h that is not acceptable :P

**Comment by cgundogan** [comment]
@miri64 your last tick removed my ticks 😩

**Comment by miri64** [comment]
gnarf I reloaded before :(

**Comment by miri64** [comment]
Sorry

**Comment by aabadie** [comment]
04-task1, 04-task2, 04-task3 and 04-task4 are done (clearly less than 1% packet loss)

**Comment by A-Paul** [comment]
> @A-Paul: when you re-did task 02.01, you also verified that the fatfs pkg is working, correct?

Every checkmark in https://github.com/RIOT-OS/Release-Specs/issues/50 is full repeated test, based on the new RC2 branch. So, yes.
To prevent further uncertainties I've added a comment.

**Comment by miri64** [comment]
> @miri64: could you confirm the ds1307 once more?

Sorry saw that only now :-/ Will do tomorrow!

**Comment by cgundogan** [comment]
Multi-hop and single-hop tests are all good. I encountered a bug in the trickle implementation (for RPL), but it's fixed and merged/backported already.

**Comment by haukepetersen** [comment]
Thanks everyone! As I see it, we should be good with testing RC2, and I'd say we are very close to getting the release out. As soon as https://github.com/RIOT-OS/RIOT/pull/7874 is merged I would like to go ahead and tag the release. Any objections?

**Comment by cgundogan** [comment]
>Any objections?

no objection from my side!

**Comment by haukepetersen** [comment]
Release is out -> done.
